# Generated by Django 4.2 on 2023-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='detail_url',
            field=models.URLField(blank=True),
        ),
    ]
